name: Build SPES Gaming Kernel

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y \
          git bc bison build-essential curl flex gcc-aarch64-linux-gnu \
          gcc-arm-linux-gnueabi libssl-dev lld make python3 zip unzip \
          clang llvm lzop rsync cpio

      - name: Clone AnyKernel3
        run: |
          git clone https://github.com/osm0sis/AnyKernel3.git AnyKernel3

      - name: Setup KernelSU
        run: |
          git clone https://github.com/tiann/KernelSU.git KernelSU

      - name: Export Environment
        run: |
          echo "ARCH=arm64" >> $GITHUB_ENV
          echo "SUBARCH=arm64" >> $GITHUB_ENV
          echo "KBUILD_BUILD_USER=NeoGPT" >> $GITHUB_ENV
          echo "KBUILD_BUILD_HOST=SPES-GAMING" >> $GITHUB_ENV

      - name: Show Defconfigs
        run: |
          find arch/arm64/configs -type f

      - name: Configure Kernel
        run: |
          make O=out ARCH=arm64 vendor/xiaomi-sm6225_defconfig

      - name: Add Gaming Config
        run: |
          echo "CONFIG_KSU=y" >> out/.config
          echo "CONFIG_KSU_KPROBES_HOOK=y" >> out/.config
          echo "CONFIG_CPU_FREQ_GOV_PERFORMANCE=y" >> out/.config
          echo "CONFIG_UCLAMP_TASK=y" >> out/.config
          echo "CONFIG_SCHED_TUNE=y" >> out/.config
          echo "CONFIG_HZ_300=y" >> out/.config
          echo "CONFIG_HZ=300" >> out/.config
          echo "CONFIG_PREEMPT=y" >> out/.config
          echo "CONFIG_TCP_CONG_BBR=y" >> out/.config

      - name: Build Kernel
        run: |
          make -j$(nproc --all) \
          O=out \
          ARCH=arm64 \
          CC=clang

      - name: Find Kernel Image
        run: |
          find out/arch/arm64/boot/

      - name: Copy Image
        run: |
          IMAGE=$(find out/arch/arm64/boot/ -name "Image.gz*" | head -n 1)

          if [ -z "$IMAGE" ]; then
            echo "Kernel image not found!"
            exit 1
          fi

          cp $IMAGE AnyKernel3/Image.gz

      - name: Create Flashable ZIP
        run: |
          cd AnyKernel3
          zip -r9 SPES-GAMING-KSU.zip *

      - name: Upload ZIP
        uses: actions/upload-artifact@v4
        with:
          name: SPES-GAMING-KSU
          path: AnyKernel3/SPES-GAMING-KSU.zip