name: Build SPES Gaming Kernel

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y \
          git bc bison build-essential flex libssl-dev \
          clang lld zip unzip python3 rsync cpio curl

      - name: Find Kernel Root
        run: |
          find . -type d | grep "arch/arm64"

      - name: Set Kernel Directory
        run: |
          KERNEL_DIR=$(find . -type d | grep "arch/arm64" | head -n1 | sed 's#/arch/arm64##')

          echo "KERNEL_DIR=$KERNEL_DIR" >> $GITHUB_ENV

          echo "Kernel dir is:"
          echo $KERNEL_DIR

      - name: Clone AnyKernel3
        run: |
          git clone https://github.com/osm0sis/AnyKernel3.git

      - name: Configure Kernel
        run: |
          cd $KERNEL_DIR

          find arch/arm64/configs -type f

          DEFCONFIG=$(find arch/arm64/configs -type f | head -n1)

          DEFNAME=$(basename $DEFCONFIG)

          echo "Using $DEFNAME"

          make O=out ARCH=arm64 $DEFNAME

      - name: Add Gaming Tweaks
        run: |
          cd $KERNEL_DIR

          echo "CONFIG_CPU_FREQ_GOV_PERFORMANCE=y" >> out/.config
          echo "CONFIG_TCP_CONG_BBR=y" >> out/.config
          echo "CONFIG_HZ_300=y" >> out/.config
          echo "CONFIG_HZ=300" >> out/.config

      - name: Build Kernel
        run: |
          cd $KERNEL_DIR

          make -j$(nproc --all) \
          O=out \
          ARCH=arm64 \
          CC=clang

      - name: Find Image
        run: |
          cd $KERNEL_DIR

          find out/arch/arm64/boot/

      - name: Copy Image
        run: |
          cd $KERNEL_DIR

          IMAGE=$(find out/arch/arm64/boot/ -name "Image*" | head -n1)

          cp $IMAGE ../../AnyKernel3/Image.gz

      - name: Create ZIP
        run: |
          cd AnyKernel3
          zip -r9 SPES-GAMING.zip *

      - name: Upload ZIP
        uses: actions/upload-artifact@v4
        with:
          name: SPES-GAMING
          path: AnyKernel3/SPES-GAMING.zip